// {
//       "id": 92,
//       "userId": 105,
//       "user": {
//         "id": 105,
//         "roleId": 1,
//         "roleName": "ADMIN",
//         "userType": "PRIEST",
//         "userName": "ML   Swany",
//         "firstName": "ML",
//         "middleName": "",
//         "lastName": " Swany",
//         "email": "mlswanyno@email.com",
//         "profileImage": null,
//         "gender": null,
//         "primaryMobile": "7702342027",
//         "alternativeMobile": "",
//         "fatherName": null,
//         "motherTongue": null,
//         "dateOfBirth": null,
//         "address": [
//           {
//             "id": 93,
//             "addressType": "Current",
//             "cityId": 1,
//             "city": {
//               "createdBy": 4,
//               "updatedBy": 4,
//               "createdAt": "2024-05-29T14:44:28.129+00:00",
//               "updatedAt": "2024-05-29T14:44:28.129+00:00",
//               "status": 1,
//               "id": 1,
//               "stateId": 1,
//               "state": {
//                 "createdBy": 4,
//                 "updatedBy": 4,
//                 "createdAt": "2024-05-29T14:44:02.188+00:00",
//                 "updatedAt": "2024-05-29T14:44:02.188+00:00",
//                 "status": 1,
//                 "id": 1,
//                 "countryId": 1,
//                 "country": {
//                   "createdBy": 4,
//                   "updatedBy": 4,
//                   "createdAt": "2024-05-29T14:43:17.491+00:00",
//                   "updatedAt": "2024-05-29T14:43:17.491+00:00",
//                   "status": 1,
//                   "id": 1,
//                   "name": "INDIA",
//                   "countryCode": "IN",
//                   "description": "india"
//                 },
//                 "name": "TELANGANA",
//                 "description": "telangana"
//               },
//               "name": "Hyderabad",
//               "description": "hyderabad"
//             },
//             "addressLine1": "Hyderabad ",
//             "addressLine2": "Hyderabad ",
//             "currentLatitude": null,
//             "currentLongitude": null,
//             "zip": null,
//             "fax": null,
//             "description": null,
//             "status": null
//           }
//         ],
//         "createdBy": 4,
//         "createdByName": null,
//         "updatedBy": 4,
//         "updatedByName": null,
//         "createdAt": "2024-05-31T11:52:33.183+00:00",
//         "updatedAt": "2024-05-31T11:52:33.183+00:00",
//         "status": 1
//       },
//       "designation": "PRIEST",
//       "yearsOfExperience": null,
//       "bio": null,
//       "taxSSN": null,
//       "description": "",
//       "createdAt": "2024-05-31T12:19:19.069+00:00",
//       "updatedAt": "2024-05-31T12:19:19.069+00:00",
//       "status": 1,
//       "priestServices": []
//     },